### ISSUE TITLE
Cannot Search Object

### ISSUE THREAD

**Issue by stborisov** [dstengele/python-insight#8]
Hello, when im trying to search object like this:

# Initialize the main Insight object with the URL and credentials for Basic Auth
insight = Insight("https://jira.example.com", ("USERNAME", "PASSWORD"))
# Get a specific object schema by ID
object_schema = InsightObjectSchema(insight, 1)
# Search for objects by IQL
objects = object_schema.search_iql("objectType = Users")

In objects i have: generator object InsightObjectSchema.search_iql at 0x000001794D04B548 not a Users

**Comment by stborisov** [comment]
insight = Insight("https://JIRAURL", ("Username", "pass"))
object_schema = InsightObjectSchema(insight, 1)
objects = object_schema.search_iql("objectType=Users")
objects
<generator object InsightObjectSchema.search_iql at 0x000001794D072D48>

------------------------------------------------------
Is it ok that i have <generator object InsightObjectSchema.search_iql at 0x000001794D072D48> in objects?
If yes, how i can recieve Users?

**Comment by dstengele** [comment]
@stborisov I have recently modified the `search_iql()` function to return a Generator instead of a list directly because with a large amount of search results this caused high RAM usage and often invoked the systems OOM killer. With the generator you can either iterate over it like this:
```python
for user in object_schema.search_iql("objectType=Users"):
    # Do something with the user object
    print(user)
```
or you can turn it into a list if you are sure that there aren't too many results:
```python
users = [user for user in object_schema.search_iql("objectType=Users")]
# Now you have a list of Insight objects like before the change
print(users)
```

I will document this behaviour soon.

**Comment by stborisov** [comment]
Thank you very much!
Now it works!
